### ISSUE TITLE
Got ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by samdark** [kikoso/android-stackblur#10]
``` java
StackBlurManager stackBlurManager = new StackBlurManager(bitmap);
stackBlurManager.process(50);
bitmap = stackBlurManager.getImage();
```

Results in:

```
java.lang.ArrayIndexOutOfBoundsException: length=665856; index=679981
            at com.enrique.stackblur.JavaBlurProcess.blur(JavaBlurProcess.java:103)
            at com.enrique.stackblur.StackBlurManager.process(StackBlurManager.java:65)
```

**Comment by aggreyjm** [comment]
java.lang.ArrayIndexOutOfBoundsException   error is seemingly unsolved on both genymotion and the real device what can do with this code below


public void getlistPopulated() {
        Cursor cursor = sqLiteDatabase.rawQuery("select * from  casual", null);

        if(cursor.moveToNext()){
            String num=cursor.getString(0);
            Toast.makeText(getBaseContext(), num,Toast.LENGTH_SHORT).show();

             String cat, dis;

                cat = cursor.getString(1);
                dis = cursor.getString(3);

                Toast.makeText(getBaseContext(), cat + dis, Toast.LENGTH_SHORT).show();
        /*    BitmapFactory.Options options = new BitmapFactory.Options();
            options.inSampleSize=8;*/
                 byte[] image = cursor.getBlob(6);
        **        Bitmap bitmap = BitmapFactory.decodeByteArray(image, 6, image.length);**
              //  Bitmap mutableBitmap = bitmap.copy(Bitmap.Config.ARGB_8888, true);
                 Bitmap scaledBitmap = Bitmap.createScaledBitmap(bitmap, bitmap.getWidth()/2, bitmap.getHeight()/2, true);
                ListDataProvider listDataProvider = new ListDataProvider(scaledBitmap ,cat, dis);
                listDataAdapter.add(listDataProvider);
        }

**Comment by Dr-Emann** [comment]
This doesn't appear to be in any way related to stackblur.
