### ISSUE TITLE
R Class problem after Reference Library

### ISSUE THREAD

**Issue by david99999** [kikoso/android-stackblur#23]
Hello, I´m getting a rare error in runtime, I´ve compiled the NDK successfully and the StackBlur (library project) compiles well, but when I reference the project library in a totally new Android Application Project something is interfering with the R Class of the new project, it compiles well but when call findviewById(R.id.textView1) returns null, I've tested the Android Project before reference the library and without it findviewById(R.id.textView1) works normally.

I´ve looking around and the people getting this error agree it is something weird with the R Class, but nobody found a really stright solution.

Can you help me with this error, please?

I really want to try this awesome blur effect with the ndk implementation.

**Comment by mozikun** [comment]
I meet the same problem！david99999 is right! 
@david99999 which file and codes should be remove？

**Comment by mozikun** [comment]
I try delete rs file and RSBlurProcess.java, and delete reference java code. It works used by Java and Native called.
