### ISSUE TITLE
Ormlite + stack blur not working

### ISSUE THREAD

**Issue by abhaysood** [kikoso/android-stackblur#30]
I'm using ormlite in the app and when i import stack blur the application stops responding.

11-04 14:07:03.646: E/AndroidRuntime(7682): FATAL EXCEPTION: main
11-04 14:07:03.646: E/AndroidRuntime(7682): Process: com.virtualx.virtualtpo, PID: 7682
11-04 14:07:03.646: E/AndroidRuntime(7682): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.virtualx.virtualtpo/com.virtualx.virtualtpo.LauncherActivity}: java.lang.IllegalStateException: Could not construct instance of helper class class com.virtualx.database.DatabaseHelper
11-04 14:07:03.646: E/AndroidRuntime(7682):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at android.app.ActivityThread.access$800(ActivityThread.java:139)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at android.os.Handler.dispatchMessage(Handler.java:102)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at android.os.Looper.loop(Looper.java:136)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at android.app.ActivityThread.main(ActivityThread.java:5086)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at java.lang.reflect.Method.invokeNative(Native Method)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at java.lang.reflect.Method.invoke(Method.java:515)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at dalvik.system.NativeStart.main(Native Method)
11-04 14:07:03.646: E/AndroidRuntime(7682): Caused by: java.lang.IllegalStateException: Could not construct instance of helper class class com.virtualx.database.DatabaseHelper
11-04 14:07:03.646: E/AndroidRuntime(7682):     at com.j256.ormlite.android.apptools.OpenHelperManager.constructHelper(OpenHelperManager.java:222)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at com.j256.ormlite.android.apptools.OpenHelperManager.loadHelper(OpenHelperManager.java:170)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at com.j256.ormlite.android.apptools.OpenHelperManager.getHelper(OpenHelperManager.java:78)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at com.virtualx.database.DatabaseQuery.isPersonalDataExisting(DatabaseQuery.java:21)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at com.virtualx.virtualtpo.LauncherActivity.onCreate(LauncherActivity.java:25)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at android.app.Activity.performCreate(Activity.java:5248)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
11-04 14:07:03.646: E/AndroidRuntime(7682):     ... 11 more
11-04 14:07:03.646: E/AndroidRuntime(7682): Caused by: java.lang.reflect.InvocationTargetException
11-04 14:07:03.646: E/AndroidRuntime(7682):     at java.lang.reflect.Constructor.constructNative(Native Method)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at com.j256.ormlite.android.apptools.OpenHelperManager.constructHelper(OpenHelperManager.java:220)
11-04 14:07:03.646: E/AndroidRuntime(7682):     ... 18 more
11-04 14:07:03.646: E/AndroidRuntime(7682): Caused by: java.lang.IllegalStateException: Could not load object config file
11-04 14:07:03.646: E/AndroidRuntime(7682):     at com.j256.ormlite.android.apptools.OrmLiteSqliteOpenHelper.<init>(OrmLiteSqliteOpenHelper.java:127)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at com.j256.ormlite.android.apptools.OrmLiteSqliteOpenHelper.<init>(OrmLiteSqliteOpenHelper.java:76)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at com.virtualx.database.DatabaseHelper.<init>(DatabaseHelper.java:65)
11-04 14:07:03.646: E/AndroidRuntime(7682):     ... 21 more
11-04 14:07:03.646: E/AndroidRuntime(7682): Caused by: java.sql.SQLException: DatabaseTableConfig reading from stream cannot parse line: ����������,���������������������������������@��m����@��������BC��!����|���������������#�A�I29��%�b�EB�B�28I
11-04 14:07:03.646: E/AndroidRuntime(7682):     at com.j256.ormlite.table.DatabaseTableConfigLoader.fromReader(DatabaseTableConfigLoader.java:74)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at com.j256.ormlite.table.DatabaseTableConfigLoader.loadDatabaseConfigFromReader(DatabaseTableConfigLoader.java:32)
11-04 14:07:03.646: E/AndroidRuntime(7682):     at com.j256.ormlite.android.apptools.OrmLiteSqliteOpenHelper.<init>(OrmLiteSqliteOpenHelper.java:125)

**Comment by ajitdubey-mob-ibtech** [comment]
did you get any solution?
