### ISSUE TITLE
Compile failure in Android Studio 1.0

### ISSUE THREAD

**Issue by wangbourne** [kikoso/android-stackblur#32]
Hate to say that but compile failure in Android studio 1.0

**Comment by rantianhua** [comment]
me too

**Comment by AshtonEngberg** [comment]
I had to update the android { buildToolsVersion value } to get it to work. (in StackBlur, not the demo, but I didn't use the demo, just the library as an imported module). Also there are some resource folders that contain ic_launcher which will conflict with your own projects (so delete them), and you can delete the application node out of the StackBlur manifest file.

**Comment by Jawnnypoo** [comment]
If you want to include via gradle, I have recompiled it and made the Native methods available through gradle. 
https://github.com/Commit451/NativeStackBlur
