### ISSUE TITLE
How to import stackblur

### ISSUE THREAD

**Issue by feresr** [kikoso/android-stackblur#37]
Download the library with git. When it has been imported into your project. First initialize your StackBlurManager to load a sample image

Could you provide more info on how to import this into android studio?. THanks

**Comment by Jawnnypoo** [comment]
If you want to include via gradle, I have recompiled it and made the Native methods available through gradle. 
https://github.com/Commit451/NativeStackBlur

**Comment by xingstarx** [comment]
@Jawnnypoo  thanks,ti's greate for me!
